spring.application.name=cruddemo

#
# JDBC properties
#
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# configure custom path
#springdoc.swagger-ui.path=/my-ui.html

# configure custom path for api docs
#springdoc.api-docs.path=/my-api-docs